spring:
  application:
    name: spring-ai-rag
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
  ai:
    mistralai:
      api-key: 0hHTXceATJsqbvVT7cepXiexjRQHEhFc
#      embedding:
#       options:
#         model: text-embedding-3-small
sfg:
  aiapp:
    vectorStorePath: C:/Users/royjo/tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv